server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  application:
    name: msvc-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: student
          uri: lb://msvc-student
          predicates:
            - Path=/api/student/**
        - id: course
          uri: lb://msvc-course
          predicates:
            - Path=/api/course/**